###
GET /user
Host: localhost:3000

###
POST /user
Host: localhost:3000
Content-Type: application/json

{
    "name":"ulises",
    "uidName":"uif",
    "rolId":2
}

###
GET /user/1
Host: localhost:3000

###
PATCH /user/1
Host: localhost:3000
Content-Type: application/json

{
    "name":"",
    "uidName":"uif",
    "rolId":2
}

###
DELETE /user/94
Host: localhost:3000


### Test Table
###
GET /test-table
Host: localhost:3000

###
POST /test-table
Host: localhost:3000
Content-Type: application/json

{
    "name":"testing",
    "flag":true,
    "list_str":["ulises", "avalos"]
}

