### Request de Tasks
GET http://localhost:3000/task/hi

###
GET http://localhost:3000/task?limite=3

###
GET http://localhost:3000/task/3

###
POST http://localhost:3000/task
Content-Type: application/json

{
    "title":"tarea3",
    "description": "hola"
}

###
PUT http://localhost:3000/task

###
PATCH http://localhost:3000/task

###
DELETE http://localhost:3000/task


### Request de Users
POST http://localhost:3000/user
Content-Type: application/json

{
    "name":"ulises",
    "age": 20,
    "email":"ulis@gmail.com",
    "password":"test"
}


### Request de PRUEBAS
GET http://localhost:3000/test/notfound
###
GET http://localhost:3000/test/errorPage
###
GET http://localhost:3000/test/new
###
GET http://localhost:3000/test/ticket/3
###
GET http://localhost:3000/test/active/true
###
GET http://localhost:3000/test/greet
?name=ulises
&age=22